apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubesystem-ingress
  namespace: kube-system
  annotations:
    nginx.org/rewrites: "serviceName=kubernetes-dashboard rewrite=/;serviceName=coffee-svc rewrite=/beans/"
spec:
  rules:
  - http:
      paths:
      - path: /dashboard
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 80
  tls:
  - hosts:
    - test.tokuapp.com
    secretName: ssl-secret
