apiVersion: v1
data:
  alertmanager.yaml: |
    global:
      # The smarthost and SMTP sender used for mail notifications.
      smtp_smarthost: 'localhost:25'
      smtp_from: 'alertmanager@example.org'
      smtp_auth_username: 'alertmanager'
      smtp_auth_password: 'password'
      # The auth token for Hipchat.
      hipchat_auth_token: 'NVjhsFzQOxFexUgULAB6Mn6FFP7TcgnFAZUrHwrp'
      # Alternative host for Hipchat.
      hipchat_url: 'https://ozgroup.hipchat.com'

    route:
      #receiver: 'slack'
      receiver: 'team-X-hipchat'
      group_by: [namespace]
      group_wait: 1m
      group_interval: 5m 
      routes:
      # All alerts with service=mysql or service=cassandra
      # are dispatched to the database pager.
      - receiver: 'team-X-hipchat'
        group_wait: 10s
        match_re:
          service: mysql|cassandra
      # All alerts with the team=frontend label match this sub-route.
      # They are grouped by product and environment rather than cluster
      # and alertname.
      - receiver: 'team-X-hipchat'
        group_by: [product, environment]
        match:
          team: frontend
    receivers:
    #    - name: 'slack'
    #      slack_configs:
    #          - send_resolved: true
    #            username: '<username>'
    #            channel: '#<channel-name>'
    #            api_url: '<incomming-webhook-url>'
     - name: 'team-X-hipchat'
       hipchat_configs:
        - auth_token: 'NVjhsFzQOxFexUgULAB6Mn6FFP7TcgnFAZUrHwrp'
          room_id: 3969483
          message_format: html
          notify: true
          send_resolved: true
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: default
